#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LiveCardDemo.Resource", IsApplication=true)]

namespace LiveCardDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int metaButtonBarButtonStyle = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int metaButtonBarStyle = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int black_overlay = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int menu_item_icon_stop = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int gestureinfo_main_content = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int livecard_content = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int menu_stop_livecarddemo = 2131296258;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_LiveCardDemo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Livecard_LiveCardDemo = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int menu_livecarddemo_livecard = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int dummy_button = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int dummy_content = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int livecarddemo_livecard_content = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int livecarddemo_localservice_started = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int livecarddemo_screen_content = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int livecarddemo_voice_prompt = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int livecarddemo_voice_trigger = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int menu_item_stop_livecarddemo = 2131099656;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int ButtonBar = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int ButtonBarButton = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int FullscreenActionBarStyle = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int FullscreenTheme = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int LiveCardDemoTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int voiceinput_livecarddemo = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ButtonBarContainerTheme = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public const int ButtonBarContainerTheme_metaButtonBarButtonStyle = 1;
			
			// aapt resource value: 0
			public const int ButtonBarContainerTheme_metaButtonBarStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
